### ISSUE TITLE
Poshtomat entity stopped working

### ISSUE THREAD

**Issue by artzillla** [krasnoukhov/homeassistant-nova-poshta#8]
Hello, 

I'm not sure if it's integration issue or not, but for some reason poshtomat entity became unavailable even though it was working previously. I created another api key just to double check if there is an issue with my key and recreated this integration from scratch, but only one entity is shown (regular branch), poshtomat is missing.

**Comment by krasnoukhov** [comment]
Thanks for the report, did you receive any parcels to the poshtomat recently?

**Comment by artzillla** [comment]
I usually get parcels on either poshtomat or regular branch - both of them are displayed in my nova poshta account. I don't remember if I had any parcels or not, but before the update it actually worked vice versa - I could see poshtomat entity only and I can confirm that I'm receiving a number of parcel in the poshtomat and didn't receive anything on the regular branch for quite a long time. Are you suggesting that API returns recent branches only? 

Anyway, after updating to the newest version I can see 2 entities for now 👍 Please let me know if you want me to close this issue! Thanks!

**Comment by krasnoukhov** [comment]
> Are you suggesting that API returns recent branches only

Yes, it does:

https://github.com/krasnoukhov/homeassistant-nova-poshta/blob/048acbbd03073f1e1e7d4003ed730d7c4d673d51/custom_components/nova_poshta/coordinator.py#L66-L69

We query the parcels for the last 2 weeks and based on that we create the sensors. Does this work for you?

**Comment by krasnoukhov** [comment]
@Vladd1980 I don't speak serbian, what are you asking?

**Comment by Vladd1980** [comment]
I don't want to create new topics and it seems to me that my question is related to this topic. I just installed the new mail integration and the only sensor available is .nova_poshta_delivered_parcels_in_****. There are no more settings. Is this how it should be?

**Comment by Vladd1980** [comment]
It's strange that you thought it was Serbian. I thought that the person who wrote the integration for the Ukrainian service definitely spoke Russian :)

**Comment by krasnoukhov** [comment]
@Vladd1980 Oh ok now I see. Yeah, that's the point of this integration - sensor per warehouse showing a number of parcels available to pick up

Yeah, I don't speak neither serbian or russian, so no difference to me really

**Comment by Vladd1980** [comment]
that is, there is no display of information that the package has been sent, when will it be delivered for example?

**Comment by Vladd1980** [comment]
There are situations when they send me a package, but I miss this moment. it would be cool if I could receive notifications from NA that a package has been sent to me, for example

**Comment by krasnoukhov** [comment]
Those are going to be feature requests

**Comment by Vladd1980** [comment]
Great! I'll be looking forward to this feature! Thank you!

**Comment by Vladd1980** [comment]
perhaps this is already arrogance, but for complete happiness I do not have enough information about where the parcel was sent from so that I could set up alerts like “owner, you have a parcel being sent from Kyiv. Arrival date...”

**Comment by krasnoukhov** [comment]
I'd suggest to create separate issue for this feature request and describe how sensor/sensors would work. I don't plan on working on this any time soon because it's not a priority for me, but maybe someone else will pick it up, or you can also submit a PR for it
